baseURL = "https://blocs.fr"
languageCode = "fr-fr"
title = "Blocs.fr - Dev. Fullstack - Software Eng. 13+ années | CTO"
theme = "zdoc"

defaultContentLanguage = "fr" # Default language to use (if you setup multilingual)
defaultContentLanguageInSubdir = false # baseURL/en/, baseURL/kr/ ...
hasCJKLanguage = false # Set `true` for Chinese/Japanese/Korean languages.

copyright = "©{year} blocs.fr" # copyright symbol: $copy; current year: {year}
timeout = 10000
enableEmoji = true
[pagination]
  pagerSize = 4
rssLimit = 100

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true
    
[taxonomies]
  tag = "tags"
